version: 2

before:
  hooks:
    - go mod tidy

builds:
  - goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '6'
      - '7'
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
    ldflags: '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser'
    mod_timestamp: "{{ .CommitTimestamp }}"